### PR TITLE
Improvement: Publish gradle plugin to gradle plugin portal

### PR DESCRIPTION
**Pull request by robert3005**
## After this PR

==COMMIT_MSG==
Publish gradle plugin to gradle plugin portal
==COMMIT_MSG==

### CODE REVIEW

**Comment by iamdanfox** [comment]
IIRC the `:palantir-java-format-spi` was a blocker to successfully publishing to the gradle plugin portal... dan had this originally: https://github.com/palantir/palantir-java-format/pull/24

**Comment by robert3005** [comment]
I really care that the gradle plugin markers are published so I could just turn on automatedpublishing and not do the rest

**Comment by robert3005** [comment]
eh, this should just work as the spi is published as a library

**Comment by iamdanfox** [comment]
Actually I think the problem before was that using the `plugins {}` syntax had a hard-coded list of repositories that it would try to load jars from, and our old bintray thing was obviously not one of them... given that we're now publishing to MavenCentral, maybe this is no longer a problem??

Think this is worth a shot, but will defer the final +1 to a current infra team member.

**Comment by robert3005** [comment]
you can always add a repo under `pluginManagement` in settings.gradle

**Review by carterkozak — APPROVED** [review]
lgtm

**Pull request merged**
